chrome:
  image: jess/chrome
  net: host               # use the host's network to reach the web
  cpuset: 0               # control the cpu
  mem_limit: 512mb        # max memory it can use
  environment:
  - DISPLAY=unix$DISPLAY  # pass the display
  volumes:
  - /tmp/.X11-unix:/tmp/.X11-unix    # mount the X11 socket
  - $HOME/Downloads:/root/Downloads  # saving the downloads in the host Download folder
